version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: BookStore/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    # depends_on:
    #   - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=db;Username=postgres;Password=123"
    ports:
      - "5152:5152"
  frontend:
    container_name: frontend
    build:
      context: ./FrontEnd/bookstore
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgres-data:
